# Generated by Django 4.1.8 on 2023-05-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mobile phone number (format: 41798257004)"
            ),
        ),
    ]
