# Generated by Django 4.1.8 on 2023-05-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0001_initial"),
        ("users", "0002_user_mobile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="club",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club"
            ),
        ),
    ]
