# Generated by Django 4.1.8 on 2023-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(choices=[(0, "None"), (1, "Partial"), (2, "Full")], default=0),
        ),
    ]
