# Generated by Django 4.1.8 on 2023-08-06 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="level",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "High performance, performance motivation"),
                            (1, "Basic performance, performance motivation"),
                            (2, "High performance, time deficit"),
                            (3, "High performance, social motivation"),
                            (4, "Basic performance, social motivation"),
                            (5, "Newcomer"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
