# Generated by Django 4.1.8 on 2023-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_user_level_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_playing",
            field=models.BooleanField(default=True),
        ),
    ]
