# Generated by Django 4.1.8 on 2023-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_userprofile_is_playing"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="permission",
            field=models.IntegerField(choices=[(0, "Player"), (1, "Coach"), (2, "Admin")], default=0),
        ),
    ]
