# Generated by Django 4.1.8 on 2023-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_userprofile_comment_alter_userprofile_abonnement"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sportlomo_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
