# Generated by Django 4.1.8 on 2023-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_userprofile_sportlomo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="sportlomo_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
