# Generated by Django 4.1.8 on 2023-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_level_classification_userprofile_classification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mobile_phone",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile_phone",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mobile phone number (format: 41798257004)"
            ),
        ),
    ]
