# Generated by Django 4.1.8 on 2023-09-07 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_userprofile_abonnement_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Level",
        ),
    ]
