# Generated by Django 4.1.8 on 2023-10-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_delete_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="positions",
            field=models.ManyToManyField(blank=True, to="users.position"),
        ),
    ]
