# Generated by Django 4.1.8 on 2025-09-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_position_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="club_hours",
            field=models.FloatField(default=0.0, help_text="Total club hours contributed by the user"),
        ),
    ]
