version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: waatea_2_production_django
    volumes:
      - production_django_media:/app/waatea_2/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`megasrv.de`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: waatea_2_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: waatea_2_production_traefik
    depends_on:
      - django
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    environment:
      - "TRAEFIK_PROVIDERS_DOCKER=true"
      - "TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false"
      - "TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80"
      - "TRAEFIK_ENTRYPOINTS_WEB_HTTPSADDRESS=:443"
      - "TRAEFIK_LOG_LEVEL=INFO"
      - "TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL=d.berger@dontsniff.co.uk"
      - "TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/etc/traefik/acme/acme.json"
      - "TRAEFIK_API_INSECURE=true"

  redis:
    image: redis:6

networks:
  traefik-public:
    external: true


#  nginx:
#    build:
#      context: .
#      dockerfile: ./compose/production/nginx/Dockerfile
#    image: waatea_2_local_nginx
#    depends_on:
#      - django
#    volumes:
#      - production_django_media:/usr/share/nginx/media:ro

