# Generated by Django 4.1.8 on 2023-05-02 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_from_club", models.BooleanField()),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("start", models.DateTimeField()),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                (
                    "away",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="away_games", to="waateaapp.team"
                    ),
                ),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="home_games", to="waateaapp.team"
                    ),
                ),
                ("season", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.season")),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.game")),
                (
                    "player",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.BooleanField()),
                (
                    "player",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("training", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.training")),
            ],
        ),
    ]
