# Generated by Django 4.1.8 on 2023-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0002_availability_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="dayofyear",
            field=models.IntegerField(default=-1),
        ),
    ]
