# Generated by Django 4.1.8 on 2023-07-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0004_remove_availability_date_remove_availability_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="season",
            field=models.ForeignKey(
                default="fe9f0c5e-b19f-4d6d-afd9-2238d67a36cb",
                on_delete=django.db.models.deletion.CASCADE,
                to="waateaapp.season",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CurrentSeason",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
                ("season", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.season")),
            ],
        ),
    ]
