# Generated by Django 4.1.8 on 2023-07-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0006_rename_state_attendance_attended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="season",
            field=models.ForeignKey(
                default="fe9f0c5e-b19f-4d6d-afd9-2238d67a36cb",
                on_delete=django.db.models.deletion.CASCADE,
                to="waateaapp.season",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="training",
            name="season",
            field=models.ForeignKey(
                default="fe9f0c5e-b19f-4d6d-afd9-2238d67a36cb",
                on_delete=django.db.models.deletion.CASCADE,
                to="waateaapp.season",
            ),
            preserve_default=False,
        ),
    ]
