# Generated by Django 4.1.8 on 2023-08-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0007_attendance_season_training_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="training",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="waateaapp.training"),
            preserve_default=False,
        ),
    ]
