# Generated by Django 4.1.8 on 2023-08-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0008_attendance_training"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="waateaapp.training"
            ),
        ),
    ]
