# Generated by Django 4.1.8 on 2023-08-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waateaapp", "0009_alter_attendance_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("home", models.CharField(max_length=200)),
                ("away", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("position", models.CharField(max_length=200)),
                ("competition", models.CharField(max_length=200)),
                (
                    "player",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
