# Generated by Django 4.1.8 on 2023-09-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waateaapp", "0009_alter_attendance_training"),
    ]

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalGame",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("played_for", models.CharField(max_length=200)),
                ("played_against", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("position", models.CharField(max_length=200)),
                ("competition", models.CharField(max_length=200)),
                (
                    "player",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("played_for", "played_against", "date", "player")},
            },
        ),
    ]
