# Generated by Django 4.1.8 on 2023-08-29 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0010_historicalgame"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalgame",
            old_name="away",
            new_name="played_against",
        ),
        migrations.RenameField(
            model_name="historicalgame",
            old_name="home",
            new_name="played_for",
        ),
    ]
