# Generated by Django 4.1.8 on 2023-09-19 22:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0010_links_historicalgame"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drill",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("link", models.CharField(max_length=200)),
                ("minplayers", models.IntegerField(default=0)),
                ("description", models.TextField(default="[]")),
            ],
        ),
        migrations.AddField(
            model_name="training",
            name="remarks",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="training",
            name="review",
            field=models.TextField(default="[]"),
        ),
        migrations.CreateModel(
            name="TrainingDrillOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField()),
                ("drill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.drill")),
                ("training", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.training")),
            ],
            options={
                "unique_together": {("training", "drill")},
            },
        ),
        migrations.CreateModel(
            name="DrillCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
            ],
        ),
        migrations.AddField(
            model_name="drill",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.drillcategory"),
        ),
        migrations.AddField(
            model_name="drill",
            name="club",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club"),
        ),
        migrations.AddField(
            model_name="training",
            name="drills",
            field=models.ManyToManyField(
                blank=True, related_name="trainings", through="waateaapp.TrainingDrillOrder", to="waateaapp.drill"
            ),
        ),
    ]
