# Generated by Django 4.1.8 on 2023-10-05 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0010_links_historicalgame"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="remarks",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="training",
            name="review",
            field=models.TextField(default="[]"),
        ),
        migrations.CreateModel(
            name="TrainingPart",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.TextField(default="")),
                ("order", models.PositiveIntegerField()),
                ("training", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.training")),
            ],
        ),
    ]
