# Generated by Django 4.1.8 on 2023-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0011_training_remarks_training_review_trainingpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingpart",
            name="minutes",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
