# Generated by Django 4.1.8 on 2023-10-18 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waateaapp", "0012_trainingpart_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineUpPos",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.IntegerField()),
                ("remarks", models.TextField(default="")),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.game")),
                (
                    "player",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "position")},
            },
        ),
    ]
