# Generated by Django 4.1.8 on 2023-09-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0012_alter_historicalgame_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("icon", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("club", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.club")),
            ],
        ),
    ]
