# Generated by Django 4.1.8 on 2023-10-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0013_lineuppos"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="lineup_published",
            field=models.BooleanField(default=False),
        ),
    ]
