# Generated by Django 4.1.8 on 2023-12-27 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waateaapp", "0014_game_lineup_published"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("player", "season", "dayofyear")},
        ),
    ]
