# Generated by Django 4.1.8 on 2024-07-17 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waateaapp", "0015_alter_availability_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fitness",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("dayofyear", models.IntegerField(default=-1)),
                ("points", models.IntegerField(default=1)),
                ("note", models.CharField(max_length=200)),
                (
                    "player",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("season", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="waateaapp.season")),
            ],
        ),
    ]
