# Generated by Django 4.1.8 on 2024-07-17 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("waateaapp", "0016_fitness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitness",
            name="dayofyear",
        ),
        migrations.AddField(
            model_name="fitness",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
