name: waatea2_client
description: Waatea 2 Client App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  random_avatar: any
  url_launcher: ^6.1.12
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
